version: "3.8"

services:
  developer-portfolio:
    build: .
    container_name: developer-portfolio
    ports:
      - "3000:8080"
    environment:
      - PORT=8080
      - IP=0.0.0.0
    env_file:
      - .env
    restart: unless-stopped
