name: Build and Push Image to Unraid Registry

on:
  push:
    branches:
      - main
      - staging
      - dev
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: [self-hosted]
    env:
      IMAGE_URL: ${{ secrets.REGISTRY_HOST_PORT }}/developer-portfolio-${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          {
            echo ""
          } > .env
      - name: Build Docker image
        run: docker build --no-cache -t ${{ env.IMAGE_URL}}:${{ github.sha }} .
      - name: Tag Docker image as latest
        run: docker tag ${{ env.IMAGE_URL}}:${{ github.sha }} ${{ env.IMAGE_URL}}:latest
      - name: Login to Docker registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_HOST_PORT }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      - name: Push Docker images
        run: docker push ${{ env.IMAGE_URL}}:${{ github.sha }}
      - name: Push Docker images
        run: docker push ${{ env.IMAGE_URL}}:latest
